# Generated by Django 5.1.3 on 2025-12-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('contribution_approved', 'Contribution Approved'), ('contribution_rejected', 'Contribution Rejected'), ('changes_requested', 'Changes Requested'), ('curator_edit', 'Curator Edit'), ('contribution_flagged', 'Contribution Flagged'), ('contribution_resubmitted', 'Contribution Resubmitted'), ('annotation_reply', 'Annotation Reply'), ('badge_earned', 'Badge Earned'), ('level_up', 'Level Up'), ('moderation_needed', 'Moderation Needed'), ('system', 'System Notification')], max_length=50, verbose_name='notification type'),
        ),
    ]
