# Generated by Django 5.1.3 on 2026-07-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_usernotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('contribution_approved', 'Contribution Approved'), ('contribution_rejected', 'Contribution Rejected'), ('changes_requested', 'Changes Requested'), ('curator_edit', 'Curator Edit'), ('contribution_flagged', 'Contribution Flagged'), ('contribution_resubmitted', 'Contribution Resubmitted'), ('annotation_reply', 'Annotation Reply'), ('category_suggestion', 'Category Suggestion'), ('badge_earned', 'Badge Earned'), ('level_up', 'Level Up'), ('moderation_needed', 'Moderation Needed'), ('system', 'System Notification')], max_length=50, verbose_name='notification type'),
        ),
    ]
