# Generated by Django 5.1.3 on 2025-12-10 06:39

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeritageItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Geographic coordinates",
                        srid=4326,
                        verbose_name="location",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="address"
                    ),
                ),
                (
                    "historical_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pre-columbian", "Pre-Columbian"),
                            ("colonial", "Colonial"),
                            ("republican", "Republican"),
                            ("contemporary", "Contemporary"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=50,
                        verbose_name="historical period",
                    ),
                ),
                (
                    "external_registry_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to official heritage registry",
                        verbose_name="external registry URL",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="view count"),
                ),
                (
                    "favorite_count",
                    models.IntegerField(default=0, verbose_name="favorite count"),
                ),
            ],
            options={
                "verbose_name": "heritage item",
                "verbose_name_plural": "heritage items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeritageRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("part_of", "Part of"),
                            ("related_to", "Related to"),
                            ("inspired_by", "Inspired by"),
                            ("located_near", "Located near"),
                            ("same_period", "Same historical period"),
                        ],
                        max_length=50,
                        verbose_name="relation type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "heritage relation",
                "verbose_name_plural": "heritage relations",
            },
        ),
        migrations.CreateModel(
            name="HeritageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "heritage type",
                "verbose_name_plural": "heritage types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="heritage/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "mp3",
                                    "wav",
                                    "mp4",
                                    "webm",
                                    "pdf",
                                ]
                            )
                        ],
                        verbose_name="file",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                        verbose_name="file type",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME type"
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="file size (bytes)"
                    ),
                ),
                (
                    "width",
                    models.IntegerField(blank=True, null=True, verbose_name="width"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="height"),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="duration"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="alternative text"
                    ),
                ),
                ("caption", models.TextField(blank=True, verbose_name="caption")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "media file",
                "verbose_name_plural": "media files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Parish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "canton",
                    models.CharField(
                        default="Riobamba", max_length=200, verbose_name="canton"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        default="Chimborazo", max_length=200, verbose_name="province"
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="boundary"
                    ),
                ),
                (
                    "population",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="population"
                    ),
                ),
                (
                    "area_km2",
                    models.FloatField(blank=True, null=True, verbose_name="area (km²)"),
                ),
            ],
            options={
                "verbose_name": "parish",
                "verbose_name_plural": "parishes",
                "ordering": ["canton", "name"],
            },
        ),
        migrations.CreateModel(
            name="HeritageCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name for frontend display",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="heritage.heritagecategory",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "heritage category",
                "verbose_name_plural": "heritage categories",
                "ordering": ["order", "name"],
            },
        ),
    ]
