# Generated by Django 5.1 on 2025-12-10 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageitem',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_heritage', to=settings.AUTH_USER_MODEL, verbose_name='moderator'),
        ),
        migrations.AddField(
            model_name='heritageitem',
            name='moderator_feedback',
            field=models.TextField(blank=True, verbose_name='moderator feedback'),
        ),
    ]
