# Generated by Django 5.1.3 on 2025-12-10 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("heritage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="heritageitem",
            name="contributor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributed_heritage",
                to=settings.AUTH_USER_MODEL,
                verbose_name="contributor",
            ),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="heritage_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="heritage_items",
                to="heritage.heritagecategory",
                verbose_name="heritage category",
            ),
        ),
        migrations.AddField(
            model_name="heritagerelation",
            name="from_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations_from",
                to="heritage.heritageitem",
                verbose_name="from item",
            ),
        ),
        migrations.AddField(
            model_name="heritagerelation",
            name="to_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations_to",
                to="heritage.heritageitem",
                verbose_name="to item",
            ),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="heritage_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="heritage_items",
                to="heritage.heritagetype",
                verbose_name="heritage type",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_media",
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploaded by",
            ),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="audio",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"file_type": "audio"},
                related_name="heritage_items_as_audio",
                to="heritage.mediafile",
                verbose_name="audio files",
            ),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"file_type": "image"},
                related_name="heritage_items_as_image",
                to="heritage.mediafile",
                verbose_name="images",
            ),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="video",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"file_type": "video"},
                related_name="heritage_items_as_video",
                to="heritage.mediafile",
                verbose_name="video files",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parish",
            unique_together={("name", "canton")},
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="parish",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="heritage_items",
                to="heritage.parish",
                verbose_name="parish",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="heritagecategory",
            unique_together={("parent", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="heritagerelation",
            unique_together={("from_item", "to_item", "relation_type")},
        ),
        migrations.AddIndex(
            model_name="heritageitem",
            index=models.Index(
                fields=["status", "-created_at"], name="heritage_he_status_fd424a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heritageitem",
            index=models.Index(
                fields=["heritage_type", "heritage_category"],
                name="heritage_he_heritag_72f49d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="heritageitem",
            index=models.Index(
                fields=["parish"], name="heritage_he_parish__d4ac30_idx"
            ),
        ),
    ]
