# Generated by Django 5.1.3 on 2025-12-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heritage", "0002_auto_20251210_1530"),
        ("heritage", "0002_initial"),
    ]

    operations = []
