# Generated by Django 5.1.3 on 2025-12-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage", "0004_alter_heritageitem_status_annotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="content_en",
            field=models.TextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="annotation",
            name="content_es",
            field=models.TextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="annotation",
            name="content_qu",
            field=models.TextField(null=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="heritagecategory",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heritagecategory",
            name="description_es",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heritagecategory",
            name="description_qu",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heritagecategory",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="heritagecategory",
            name="name_es",
            field=models.CharField(max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="heritagecategory",
            name="name_qu",
            field=models.CharField(max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="address_en",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="address"
            ),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="address_es",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="address"
            ),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="address_qu",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="address"
            ),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="description_en",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="description_es",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="description_qu",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="title_en",
            field=models.CharField(max_length=500, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="title_es",
            field=models.CharField(max_length=500, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="heritageitem",
            name="title_qu",
            field=models.CharField(max_length=500, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="heritagetype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heritagetype",
            name="description_es",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heritagetype",
            name="description_qu",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="heritagetype",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="heritagetype",
            name="name_es",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="heritagetype",
            name="name_qu",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="parish",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="parish",
            name="name_es",
            field=models.CharField(max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="parish",
            name="name_qu",
            field=models.CharField(max_length=200, null=True, verbose_name="name"),
        ),
    ]
