# Generated by Django 5.1.3 on 2025-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage", "0005_annotation_content_en_annotation_content_es_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="heritageitem",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"file_type": "document"},
                related_name="heritage_items_as_document",
                to="heritage.mediafile",
                verbose_name="documents",
            ),
        ),
    ]

