# Generated by Django 5.1.3 on 2025-12-13 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0006_heritageitem_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageitem',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_heritage', to=settings.AUTH_USER_MODEL, verbose_name='curator'),
        ),
        migrations.AddField(
            model_name='heritageitem',
            name='curator_feedback',
            field=models.TextField(blank=True, verbose_name='curator feedback'),
        ),
        migrations.AddField(
            model_name='heritageitem',
            name='last_review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last review date'),
        ),
        migrations.AddField(
            model_name='heritageitem',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='heritageitem',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='submission date'),
        ),
        migrations.AlterField(
            model_name='heritageitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('changes_requested', 'Changes Requested'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='heritageitem',
            index=models.Index(fields=['status', '-submission_date'], name='heritage_he_status_7d0571_idx'),
        ),
        migrations.AddIndex(
            model_name='heritageitem',
            index=models.Index(fields=['curator', 'status'], name='heritage_he_curator_baddc7_idx'),
        ),
        migrations.AddIndex(
            model_name='heritageitem',
            index=models.Index(fields=['priority', '-submission_date'], name='heritage_he_priorit_6342de_idx'),
        ),
    ]
