# Generated by OpenAI Codex CLI on 2025-12-13

from django.db import migrations


def backfill_curator_fields(apps, schema_editor):
    HeritageItem = apps.get_model("heritage", "HeritageItem")

    qs = HeritageItem.objects.all()
    for item in qs.iterator():
        update_fields = []

        if getattr(item, "curator_id", None) is None and getattr(item, "moderator_id", None) is not None:
            item.curator_id = item.moderator_id
            update_fields.append("curator")

        if getattr(item, "curator_feedback", "") == "" and getattr(item, "moderator_feedback", ""):
            item.curator_feedback = item.moderator_feedback
            update_fields.append("curator_feedback")

        if getattr(item, "submission_date", None) is None and getattr(item, "created_at", None) is not None:
            item.submission_date = item.created_at
            update_fields.append("submission_date")

        if getattr(item, "last_review_date", None) is None:
            if getattr(item, "moderator_id", None) is not None:
                item.last_review_date = item.updated_at
                update_fields.append("last_review_date")
            elif getattr(item, "status", "") in ("published", "rejected", "archived"):
                item.last_review_date = item.updated_at
                update_fields.append("last_review_date")

        if update_fields:
            item.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("heritage", "0007_heritageitem_curator_heritageitem_curator_feedback_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_curator_fields, migrations.RunPython.noop),
    ]

