# Generated by Django 5.1.3 on 2025-12-14 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage", "0008_backfill_governance_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="content_qu",
        ),
        migrations.RemoveField(
            model_name="heritagecategory",
            name="description_qu",
        ),
        migrations.RemoveField(
            model_name="heritagecategory",
            name="name_qu",
        ),
        migrations.RemoveField(
            model_name="heritageitem",
            name="address_qu",
        ),
        migrations.RemoveField(
            model_name="heritageitem",
            name="description_qu",
        ),
        migrations.RemoveField(
            model_name="heritageitem",
            name="title_qu",
        ),
        migrations.RemoveField(
            model_name="heritagetype",
            name="description_qu",
        ),
        migrations.RemoveField(
            model_name="heritagetype",
            name="name_qu",
        ),
        migrations.RemoveField(
            model_name="parish",
            name="name_qu",
        ),
        migrations.AddField(
            model_name="mediafile",
            name="text_content",
            field=models.TextField(blank=True, verbose_name="text content"),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="heritage/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "mp3",
                            "wav",
                            "mp4",
                            "webm",
                            "pdf",
                            "txt",
                        ]
                    )
                ],
                verbose_name="file",
            ),
        ),
    ]
