# Generated by Django 5.1.3 on 2025-12-15 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage", "0010_alter_mediafile_uploaded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="heritage/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "mp3",
                            "wav",
                            "mp4",
                            "webm",
                            "pdf",
                            "txt",
                            "html",
                        ]
                    )
                ],
                verbose_name="file",
            ),
        ),
    ]
