# Generated by Django 5.1.3 on 2025-12-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0011_alter_mediafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageitem',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heritage_items_main', to='heritage.mediafile', verbose_name='main image'),
        ),
    ]
