# Generated by Django 5.1.3 on 2026-07-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_backfill_riobamba_city_roles'),
        ('heritage', '0012_heritageitem_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageitem',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heritage_items', to='cities.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='parish',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parishes', to='cities.city', verbose_name='city'),
        ),
    ]
