# Generated by Django 5.1.3 on 2026-07-08 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_backfill_riobamba_city_roles'),
        ('heritage', '0014_backfill_city_riobamba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parish',
            options={'ordering': ['city', 'name'], 'verbose_name': 'parish', 'verbose_name_plural': 'parishes'},
        ),
        migrations.AlterUniqueTogether(
            name='parish',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='heritageitem',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heritage_items', to='cities.city', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='canton',
            field=models.CharField(blank=True, max_length=200, verbose_name='canton'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parishes', to='cities.city', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='province',
            field=models.CharField(blank=True, max_length=200, verbose_name='province'),
        ),
        migrations.AlterUniqueTogether(
            name='parish',
            unique_together={('name', 'city')},
        ),
        migrations.AddIndex(
            model_name='heritageitem',
            index=models.Index(fields=['city', 'status'], name='heritage_he_city_id_f63fd0_idx'),
        ),
    ]
