# Generated by Django 5.1.3 on 2026-07-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0015_require_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='heritageitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='heritage_items', to='heritage.tag', verbose_name='tags'),
        ),
    ]
