# Generated by OpenAI Codex CLI on 2025-12-13

from django.db import migrations


def seed_roles_and_assign_profiles(apps, schema_editor):
    User = apps.get_model("users", "User")
    UserProfile = apps.get_model("users", "UserProfile")
    UserRole = apps.get_model("users", "UserRole")

    roles = {
        "curator": {
            "name": "Curator",
            "permissions": {
                "can_review_contributions": True,
                "can_edit_contributions": True,
                "can_flag_content": True,
                "can_access_internal_notes": True,
                "can_approve_reject": True,
            },
            "description": "Reviews and manages user contributions",
        },
        "teacher": {
            "name": "Teacher",
            "permissions": {
                "can_download_lom": True,
                "can_access_educational_content": True,
            },
            "description": "Educator with special access to educational resources",
        },
        "contributor": {
            "name": "Contributor",
            "permissions": {
                "can_submit_contributions": True,
                "can_edit_own_contributions": True,
                "can_resubmit_rejected": True,
            },
            "description": "Regular user who can submit heritage contributions",
        },
    }

    role_objs = {}
    for slug, role_data in roles.items():
        obj, _ = UserRole.objects.update_or_create(
            slug=slug,
            defaults={
                "name": role_data["name"],
                "permissions": role_data["permissions"],
                "description": role_data["description"],
            },
        )
        role_objs[slug] = obj

    curator_role = role_objs["curator"]
    contributor_role = role_objs["contributor"]

    for user in User.objects.all().iterator():
        profile, _ = UserProfile.objects.get_or_create(user=user, defaults={"preferred_language": "es"})
        if user.is_staff:
            profile.role = curator_role
        else:
            if profile.role_id is None:
                profile.role = contributor_role
        profile.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RunPython(seed_roles_and_assign_profiles, migrations.RunPython.noop),
    ]

