# Generated by Django 5.1.3 on 2025-12-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seed_core_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='User interests topics', verbose_name='interests'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=5, verbose_name='preferred language'),
        ),
    ]
