# Generated by Django 5.1.3 on 2025-12-13 17:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heritage', '0007_heritageitem_curator_heritageitem_curator_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='is pinned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator_notes', to=settings.AUTH_USER_MODEL, verbose_name='curator')),
                ('heritage_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator_notes', to='heritage.heritageitem', verbose_name='heritage item')),
            ],
            options={
                'verbose_name': 'curator note',
                'verbose_name_plural': 'curator notes',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeness_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='completeness score')),
                ('accuracy_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='accuracy score')),
                ('media_quality_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='media quality score')),
                ('total_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='total score')),
                ('scored_at', models.DateTimeField(auto_now=True, verbose_name='scored at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('heritage_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_score', to='heritage.heritageitem', verbose_name='heritage item')),
                ('scored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_scores', to=settings.AUTH_USER_MODEL, verbose_name='scored by')),
            ],
            options={
                'verbose_name': 'quality score',
                'verbose_name_plural': 'quality scores',
            },
        ),
        migrations.CreateModel(
            name='ReviewChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('applicable_to_categories', models.ManyToManyField(blank=True, related_name='review_checklists', to='heritage.heritagecategory', verbose_name='applicable to categories')),
                ('applicable_to_types', models.ManyToManyField(blank=True, related_name='review_checklists', to='heritage.heritagetype', verbose_name='applicable to types')),
            ],
            options={
                'verbose_name': 'review checklist',
                'verbose_name_plural': 'review checklists',
            },
        ),
        migrations.CreateModel(
            name='ReviewChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='text')),
                ('help_text', models.TextField(blank=True, verbose_name='help text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_required', models.BooleanField(default=False, verbose_name='is required')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='moderation.reviewchecklist', verbose_name='checklist')),
            ],
            options={
                'verbose_name': 'review checklist item',
                'verbose_name_plural': 'review checklist items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContributionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate'), ('duplicate', 'Duplicate'), ('expert_review_needed', 'Expert Review Needed'), ('copyright_issue', 'Copyright Issue'), ('inaccurate', 'Inaccurate')], max_length=30, verbose_name='flag type')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20, verbose_name='status')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='resolution notes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_created', to=settings.AUTH_USER_MODEL, verbose_name='flagged by')),
                ('heritage_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='heritage.heritageitem', verbose_name='heritage item')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_resolved', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
            ],
            options={
                'verbose_name': 'contribution flag',
                'verbose_name_plural': 'contribution flags',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='moderation__status_39a420_idx'), models.Index(fields=['heritage_item', 'status'], name='moderation__heritag_403674_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContributionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='version number')),
                ('created_by_type', models.CharField(choices=[('contributor', 'Contributor'), ('curator', 'Curator'), ('system', 'System')], default='contributor', max_length=20, verbose_name='created by type')),
                ('data_snapshot', models.JSONField(default=dict, verbose_name='data snapshot')),
                ('changes_summary', models.TextField(blank=True, verbose_name='changes summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('heritage_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='heritage.heritageitem', verbose_name='heritage item')),
            ],
            options={
                'verbose_name': 'contribution version',
                'verbose_name_plural': 'contribution versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['heritage_item', '-version_number'], name='moderation__heritag_ff4d91_idx')],
                'constraints': [models.UniqueConstraint(fields=('heritage_item', 'version_number'), name='unique_version_per_heritage_item')],
            },
        ),
        migrations.CreateModel(
            name='ReviewChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='is checked')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='moderation.reviewchecklistitem', verbose_name='checklist item')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_responses', to=settings.AUTH_USER_MODEL, verbose_name='curator')),
                ('heritage_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='heritage.heritageitem', verbose_name='heritage item')),
            ],
            options={
                'verbose_name': 'review checklist response',
                'verbose_name_plural': 'review checklist responses',
                'constraints': [models.UniqueConstraint(fields=('heritage_item', 'checklist_item', 'curator'), name='unique_checklist_response_per_user')],
            },
        ),
    ]
