# Generated by OpenAI Codex CLI on 2025-12-13

from django.db import migrations


def seed_default_review_checklist(apps, schema_editor):
    ReviewChecklist = apps.get_model("moderation", "ReviewChecklist")
    ReviewChecklistItem = apps.get_model("moderation", "ReviewChecklistItem")

    checklist, _ = ReviewChecklist.objects.get_or_create(
        name="Default Review Checklist",
        defaults={
            "description": "Baseline curator checklist for reviewing heritage contributions.",
            "is_active": True,
        },
    )

    items = [
        ("Historical accuracy verified", True),
        ("Proper heritage type and category selected", True),
        ("Media files meet quality standards", True),
        ("Location coordinates are accurate", True),
        ("Description provides sufficient context", True),
        ("External references cited", False),
        ("No copyright or legal issues detected", True),
    ]

    for order, (text, is_required) in enumerate(items, start=1):
        ReviewChecklistItem.objects.get_or_create(
            checklist=checklist,
            text=text,
            defaults={
                "order": order,
                "is_required": is_required,
                "help_text": "",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_default_review_checklist, migrations.RunPython.noop),
    ]

