# Generated by OpenAI Codex CLI on 2025-12-13

from django.db import migrations


def _serialize_media(qs):
    rows = list(
        qs.values(
            "id",
            "file",
            "file_type",
            "mime_type",
            "size",
            "width",
            "height",
            "duration",
            "alt_text",
            "caption",
            "created_at",
        )
    )
    for row in rows:
        if row.get("id") is not None:
            row["id"] = str(row["id"])
        if row.get("created_at") is not None:
            row["created_at"] = row["created_at"].isoformat()
        if row.get("duration") is not None:
            row["duration"] = row["duration"].total_seconds()
    return rows


def _serialize_location(point):
    if not point:
        return None
    return {"lat": point.y, "lng": point.x}


def create_initial_versions(apps, schema_editor):
    HeritageItem = apps.get_model("heritage", "HeritageItem")
    ContributionVersion = apps.get_model("moderation", "ContributionVersion")

    qs = (
        HeritageItem.objects.filter(versions__isnull=True)
        .select_related("parish", "heritage_type", "heritage_category", "contributor", "curator")
        .prefetch_related("images", "audio", "video", "documents")
        .order_by("created_at")
    )

    to_create = []
    for item in qs.iterator(chunk_size=200):
        snapshot = {
            "id": str(item.id),
            "title": item.title,
            "description": item.description,
            "status": item.status,
            "location": _serialize_location(getattr(item, "location", None)),
            "address": item.address,
            "parish": (
                {"id": item.parish_id, "name": getattr(item.parish, "name", None)} if item.parish_id else None
            ),
            "heritage_type": (
                {"id": item.heritage_type_id, "name": getattr(item.heritage_type, "name", None)}
                if item.heritage_type_id
                else None
            ),
            "heritage_category": (
                {"id": str(item.heritage_category_id), "name": getattr(item.heritage_category, "name", None)}
                if item.heritage_category_id
                else None
            ),
            "historical_period": item.historical_period,
            "external_registry_url": item.external_registry_url,
            "contributor_id": item.contributor_id,
            "curator_id": item.curator_id,
            "curator_feedback": getattr(item, "curator_feedback", ""),
            "priority": getattr(item, "priority", 0),
            "submission_date": item.submission_date.isoformat() if item.submission_date else None,
            "last_review_date": item.last_review_date.isoformat() if item.last_review_date else None,
            "created_at": item.created_at.isoformat() if item.created_at else None,
            "updated_at": item.updated_at.isoformat() if item.updated_at else None,
            "media": {
                "images": _serialize_media(item.images.all()),
                "audio": _serialize_media(item.audio.all()),
                "video": _serialize_media(item.video.all()),
                "documents": _serialize_media(item.documents.all()),
            },
        }

        created_by_type = "contributor" if item.contributor_id else "system"
        to_create.append(
            ContributionVersion(
                heritage_item=item,
                version_number=1,
                created_by=item.contributor if item.contributor_id else None,
                created_by_type=created_by_type,
                data_snapshot=snapshot,
                changes_summary="Initial submission",
            )
        )

    if to_create:
        ContributionVersion.objects.bulk_create(to_create, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0002_seed_default_review_checklist"),
        ("heritage", "0008_backfill_governance_fields"),
    ]

    operations = [
        migrations.RunPython(create_initial_versions, migrations.RunPython.noop),
    ]
