# Generated by Django 5.1.3 on 2025-12-10 17:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heritage', '0005_annotation_content_en_annotation_content_es_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('theme', models.CharField(blank=True, max_length=100, verbose_name='theme')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20, verbose_name='difficulty')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='estimated duration')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='distance (km)')),
                ('path', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='path')),
                ('is_official', models.BooleanField(default=False, verbose_name='is official')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'heritage route',
                'verbose_name_plural': 'heritage routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('arrival_instructions', models.TextField(blank=True, verbose_name='arrival instructions')),
                ('suggested_time', models.DurationField(blank=True, null=True, verbose_name='suggested time')),
                ('heritage_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='heritage.heritageitem')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.heritageroute')),
            ],
            options={
                'verbose_name': 'route stop',
                'verbose_name_plural': 'route stops',
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'heritage_item')},
            },
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='items',
            field=models.ManyToManyField(related_name='routes', through='routes.RouteStop', to='heritage.heritageitem', verbose_name='heritage items'),
        ),
        migrations.CreateModel(
            name='UserRouteProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('current_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='routes.routestop', verbose_name='current stop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='routes.heritageroute', verbose_name='route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_progress', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('visited_stops', models.ManyToManyField(blank=True, related_name='visited_by_users', to='routes.routestop', verbose_name='visited stops')),
            ],
            options={
                'verbose_name': 'user route progress',
                'verbose_name_plural': 'user route progress',
                'unique_together': {('user', 'route')},
            },
        ),
    ]
