# Generated by Django 5.1.3 on 2025-12-13 19:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage", "0008_backfill_governance_fields"),
        ("routes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rating",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "route rating",
                "verbose_name_plural": "route ratings",
            },
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="accessibility_notes",
            field=models.TextField(blank=True, verbose_name="accessibility notes"),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="available_languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Array of language codes, e.g., ["es", "en", "qu"]',
                verbose_name="available languages",
            ),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="average_rating",
            field=models.FloatField(
                blank=True, null=True, verbose_name="average rating"
            ),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="best_season",
            field=models.CharField(
                blank=True,
                choices=[
                    ("spring", "Spring"),
                    ("summer", "Summer"),
                    ("autumn", "Autumn"),
                    ("winter", "Winter"),
                    ("year_round", "Year Round"),
                ],
                max_length=50,
                verbose_name="best season",
            ),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="completion_count",
            field=models.IntegerField(default=0, verbose_name="completion count"),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="cost_notes",
            field=models.TextField(blank=True, verbose_name="cost notes"),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="curator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curated_routes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="curator",
            ),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="curator_feedback",
            field=models.TextField(blank=True, verbose_name="curator feedback"),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="estimated cost",
            ),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="last_review_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last review date"
            ),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="priority"),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="public_transit_accessible",
            field=models.BooleanField(
                default=False, verbose_name="public transit accessible"
            ),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="submission_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="submission date"
            ),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="view count"),
        ),
        migrations.AddField(
            model_name="heritageroute",
            name="wheelchair_accessible",
            field=models.BooleanField(
                default=False, verbose_name="wheelchair accessible"
            ),
        ),
        migrations.AlterField(
            model_name="heritageroute",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("changes_requested", "Changes Requested"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddIndex(
            model_name="heritageroute",
            index=models.Index(
                fields=["status", "-created_at"], name="routes_heri_status_67c4ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heritageroute",
            index=models.Index(
                fields=["creator", "status"], name="routes_heri_creator_7684e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heritageroute",
            index=models.Index(
                fields=["-view_count"], name="routes_heri_view_co_230b72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heritageroute",
            index=models.Index(
                fields=["-completion_count"], name="routes_heri_complet_85598f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heritageroute",
            index=models.Index(
                fields=["is_official", "status"], name="routes_heri_is_offi_2a5ba7_idx"
            ),
        ),
        migrations.AddField(
            model_name="routerating",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="routes.heritageroute",
                verbose_name="route",
            ),
        ),
        migrations.AddField(
            model_name="routerating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_ratings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="routerating",
            index=models.Index(
                fields=["route", "-created_at"], name="routes_rout_route_i_b5e2f9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routerating",
            unique_together={("route", "user")},
        ),
    ]
