# Generated by Django 5.1.3 on 2025-12-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_routerating_heritageroute_accessibility_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heritageroute",
            name="available_languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Array of language codes, e.g., ["es", "en"]',
                verbose_name="available languages",
            ),
        ),
    ]
