# Generated by Django 5.1.3 on 2026-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_heritageroute_available_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageroute',
            name='accessibility_notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='accessibility notes'),
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='accessibility_notes_es',
            field=models.TextField(blank=True, null=True, verbose_name='accessibility notes'),
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='cost_notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='cost notes'),
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='cost_notes_es',
            field=models.TextField(blank=True, null=True, verbose_name='cost notes'),
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='description_es',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='theme_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='theme'),
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='theme_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='theme'),
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='turn_by_turn',
            field=models.JSONField(blank=True, default=list, verbose_name='turn-by-turn directions'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='arrival_instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='arrival instructions'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='arrival_instructions_es',
            field=models.TextField(blank=True, null=True, verbose_name='arrival instructions'),
        ),
    ]
