# Generated by Django 5.1.3 on 2026-07-01 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_heritageroute_accessibility_notes_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='color')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'route theme',
                'verbose_name_plural': 'route themes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='heritageroute',
            name='theme_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='routes.routetheme', verbose_name='theme category'),
        ),
    ]
