# Generated by Django 5.1.3 on 2026-07-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_backfill_riobamba_city_roles'),
        ('routes', '0006_seed_route_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageroute',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='cities.city', verbose_name='city'),
        ),
    ]
