# Generated by Django 5.1.3 on 2026-07-08 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_backfill_riobamba_city_roles'),
        ('heritage', '0015_require_city'),
        ('routes', '0008_backfill_city_riobamba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritageroute',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='cities.city', verbose_name='city'),
        ),
        migrations.AddIndex(
            model_name='heritageroute',
            index=models.Index(fields=['city', 'status'], name='routes_heri_city_id_1dbf52_idx'),
        ),
    ]
