# Generated by Django 5.1.3 on 2026-07-08 09:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_es', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('country', models.CharField(default='EC', help_text='ISO 3166-1 alpha-2 country code, e.g. EC, PE, ES', max_length=2, verbose_name='country code')),
                ('country_name', models.CharField(default='Ecuador', max_length=100, verbose_name='country name')),
                ('country_name_es', models.CharField(default='Ecuador', max_length=100, null=True, verbose_name='country name')),
                ('country_name_en', models.CharField(default='Ecuador', max_length=100, null=True, verbose_name='country name')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='region/province')),
                ('timezone', models.CharField(default='America/Guayaquil', help_text='IANA timezone name, e.g. America/Guayaquil', max_length=64, verbose_name='timezone')),
                ('center', django.contrib.gis.db.models.fields.PointField(help_text='Default map center for this city', srid=4326, verbose_name='map center')),
                ('default_zoom', models.PositiveSmallIntegerField(default=13, verbose_name='default zoom')),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='boundary')),
                ('default_language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5, verbose_name='default language')),
                ('hero_image', models.ImageField(blank=True, help_text='Landing-page hero image for this city', null=True, upload_to='cities/heroes/', verbose_name='hero image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.IntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CityRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('curator', 'Curator'), ('moderator', 'Moderator')], max_length=20, verbose_name='role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='cities.city', verbose_name='city')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_city_roles', to=settings.AUTH_USER_MODEL, verbose_name='granted by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_roles', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'city role',
                'verbose_name_plural': 'city roles',
                'indexes': [models.Index(fields=['user', 'role'], name='cities_city_user_id_0d03b1_idx'), models.Index(fields=['city', 'role'], name='cities_city_city_id_d69ca4_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'city', 'role'), name='unique_user_city_role')],
            },
        ),
    ]
