# Generated by Django 5.1.3 on 2026-07-09 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_backfill_riobamba_city_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='brand_color',
            field=models.CharField(blank=True, help_text='Hex color like #b55a3a; used as the accent color in the app', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a #RRGGBB hex color.')], verbose_name='brand color'),
        ),
        migrations.AddField(
            model_name='city',
            name='logo',
            field=models.ImageField(blank=True, help_text='Small square-ish logo shown next to the platform brand', null=True, upload_to='cities/logos/', verbose_name='logo'),
        ),
    ]
