# Generated by Django 5.1.3 on 2026-07-21 13:25

import apps.cities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_city_brand_color_city_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, validators=[apps.cities.models.validate_city_slug], verbose_name='slug'),
        ),
    ]
