# Generated by Django 5.1.3 on 2025-12-10 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heritage', '0005_annotation_content_en_annotation_content_es_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contribution_type', models.CharField(choices=[('new_item', 'New Heritage Item'), ('enrichment', 'Enrichment (Media/Info)'), ('correction', 'Correction')], max_length=50, verbose_name='contribution type')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', max_length=50, verbose_name='status')),
                ('content', models.JSONField(default=dict, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='contributor')),
                ('heritage_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='heritage.heritageitem', verbose_name='heritage item')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contributions', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'contribution',
                'verbose_name_plural': 'contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_changes', 'Request Changes')], max_length=50, verbose_name='decision')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contributions.contribution', verbose_name='contribution')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'contribution review',
                'verbose_name_plural': 'contribution reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
