# Generated by Django 5.1.3 on 2026-07-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionreview',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='contributionreview',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='ContributionReview',
        ),
    ]
