# Generated by Django 5.1.3 on 2025-12-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="points")),
                ("reason", models.CharField(max_length=500, verbose_name="reason")),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Content type of related object",
                        max_length=100,
                        verbose_name="reference type",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of related object",
                        max_length=255,
                        verbose_name="reference ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "point transaction",
                "verbose_name_plural": "point transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
