# Generated by Django 5.1.3 on 2025-12-10 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Delete and recreate PointTransaction with UUID primary key
        migrations.DeleteModel(
            name="PointTransaction",
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="badges/", verbose_name="icon"
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="category")),
                (
                    "points_value",
                    models.IntegerField(default=0, verbose_name="points value"),
                ),
                (
                    "requirements",
                    models.JSONField(default=dict, verbose_name="requirements"),
                ),
            ],
            options={
                "verbose_name": "badge",
                "verbose_name_plural": "badges",
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.IntegerField(unique=True, verbose_name="number")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("min_points", models.IntegerField(verbose_name="minimum points")),
                ("max_points", models.IntegerField(verbose_name="maximum points")),
                ("benefits", models.JSONField(default=dict, verbose_name="benefits")),
            ],
            options={
                "verbose_name": "level",
                "verbose_name_plural": "levels",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points", models.IntegerField(verbose_name="points")),
                ("reason", models.CharField(max_length=500, verbose_name="reason")),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Content type of related object",
                        max_length=100,
                        verbose_name="reference type",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of related object",
                        max_length=255,
                        verbose_name="reference ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "point transaction",
                "verbose_name_plural": "point transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="earned at"),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="gamification.badge",
                        verbose_name="badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user badge",
                "verbose_name_plural": "user badges",
                "unique_together": {("user", "badge")},
            },
        ),
    ]
