# Generated by Codex CLI
from django.db import migrations


def seed_levels(apps, schema_editor):
    Level = apps.get_model("gamification", "Level")
    levels = [
        {
            "number": 1,
            "name": "Explorador",
            "min_points": 0,
            "max_points": 99,
            "benefits": {"access": "Basic access"},
        },
        {
            "number": 2,
            "name": "Descubridor",
            "min_points": 100,
            "max_points": 299,
            "benefits": {"features": ["Can annotate"]},
        },
        {
            "number": 3,
            "name": "Guardián",
            "min_points": 300,
            "max_points": 699,
            "benefits": {"features": ["Can create routes"]},
        },
        {
            "number": 4,
            "name": "Cronista",
            "min_points": 700,
            "max_points": 1499,
            "benefits": {"features": ["Early access to features"]},
        },
        {
            "number": 5,
            "name": "Embajador",
            "min_points": 1500,
            "max_points": 2999,
            "benefits": {"features": ["Moderation privileges"]},
        },
        {
            "number": 6,
            "name": "Maestro",
            "min_points": 3000,
            "max_points": 999999,
            "benefits": {"features": ["Featured contributor"]},
        },
    ]

    for level in levels:
        Level.objects.update_or_create(number=level["number"], defaults=level)


def seed_badges(apps, schema_editor):
    Badge = apps.get_model("gamification", "Badge")
    badges = [
        # Contribution badges
        {
            "name": "Primer Aporte",
            "category": "Contribution",
            "description": "Primer aporte realizado por el usuario.",
            "points_value": 0,
            "requirements": {"type": "contributions", "count": 1},
        },
        {
            "name": "Prolífico",
            "category": "Contribution",
            "description": "10 contribuciones realizadas.",
            "points_value": 0,
            "requirements": {"type": "contributions", "count": 10},
        },
        {
            "name": "Experto Local",
            "category": "Contribution",
            "description": "50 contribuciones realizadas.",
            "points_value": 0,
            "requirements": {"type": "contributions", "count": 50},
        },
        # Exploration badges
        {
            "name": "Caminante",
            "category": "Exploration",
            "description": "Completa 5 rutas.",
            "points_value": 0,
            "requirements": {"type": "routes_completed", "count": 5},
        },
        {
            "name": "Peregrino",
            "category": "Exploration",
            "description": "Completa 20 rutas.",
            "points_value": 0,
            "requirements": {"type": "routes_completed", "count": 20},
        },
        {
            "name": "Todas las Parroquias",
            "category": "Exploration",
            "description": "Visita todas las parroquias registradas.",
            "points_value": 0,
            "requirements": {"type": "parishes", "goal": "all"},
        },
        # Quality badges
        {
            "name": "Detallista",
            "category": "Quality",
            "description": "5 contribuciones con metadatos completos.",
            "points_value": 0,
            "requirements": {"type": "high_quality_contributions", "count": 5},
        },
        {
            "name": "Fotógrafo",
            "category": "Quality",
            "description": "10 contribuciones con imágenes de alta calidad.",
            "points_value": 0,
            "requirements": {"type": "photo_contributions", "count": 10},
        },
        {
            "name": "Historiador",
            "category": "Quality",
            "description": "Contribuciones citadas por educadores.",
            "points_value": 0,
            "requirements": {"type": "educator_citations", "count": 1},
        },
        # Community badges
        {
            "name": "Colaborador",
            "category": "Community",
            "description": "10 anotaciones en items de otros usuarios.",
            "points_value": 0,
            "requirements": {"type": "annotations", "count": 10},
        },
        {
            "name": "Mentor",
            "category": "Community",
            "description": "Ayuda a 5 nuevos usuarios.",
            "points_value": 0,
            "requirements": {"type": "mentorships", "count": 5},
        },
        {
            "name": "Verificador",
            "category": "Community",
            "description": "20 revisiones de contribuciones.",
            "points_value": 0,
            "requirements": {"type": "reviews", "count": 20},
        },
        # Special badges
        {
            "name": "Pionero",
            "category": "Special",
            "description": "Usuario de adopción temprana.",
            "points_value": 0,
            "requirements": {"type": "special", "slug": "early_adopter"},
        },
        {
            "name": "Evento Especial",
            "category": "Special",
            "description": "Participación en eventos de patrimonio.",
            "points_value": 0,
            "requirements": {"type": "special", "slug": "event"},
        },
    ]

    for badge in badges:
        defaults = badge.copy()
        name = defaults.pop("name")
        Badge.objects.update_or_create(name=name, defaults=defaults)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0003_badge_level_alter_pointtransaction_id_userbadge"),
    ]

    operations = [
        migrations.RunPython(seed_levels, reverse_code=noop),
        migrations.RunPython(seed_badges, reverse_code=noop),
    ]
