# Generated by Django 5.1.3 on 2026-07-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_aiusagerecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusagerecord',
            new_name='ai_services_created_3e2266_idx',
            old_name='ai_services_created_2e0f6f_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagerecord',
            new_name='ai_services_user_id_0491b9_idx',
            old_name='ai_services_user_id_9b1a3c_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagerecord',
            new_name='ai_services_operati_f530c5_idx',
            old_name='ai_services_operati_4d7e21_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagerecord',
            new_name='ai_services_provide_c5a2de_idx',
            old_name='ai_services_provide_a3f8b2_idx',
        ),
    ]
