# Generated by Django 5.1.3 on 2026-07-08 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0003_rename_ai_services_created_2e0f6f_idx_ai_services_created_3e2266_idx_and_more'),
        ('cities', '0003_backfill_riobamba_city_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagerecord',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cities.city', verbose_name='city'),
        ),
        migrations.AddIndex(
            model_name='aiusagerecord',
            index=models.Index(fields=['city', 'created_at'], name='ai_services_city_id_dc92b1_idx'),
        ),
    ]
