# Generated by Django 5.1.3 on 2025-12-10 07:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("heritage", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LOMGeneral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Name given to this learning object",
                        max_length=500,
                        verbose_name="title",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("es", "Spanish"),
                            ("en", "English"),
                            ("qu", "Quechua"),
                        ],
                        default="es",
                        help_text="Primary language of the learning object",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the content of this learning object",
                        verbose_name="description",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Keywords or phrases describing the topic (comma-separated)",
                        verbose_name="keywords",
                    ),
                ),
                (
                    "coverage",
                    models.TextField(
                        blank=True,
                        help_text="Time, culture, geography or region to which this learning object applies",
                        verbose_name="coverage",
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        choices=[
                            ("atomic", "Atomic - indivisible object"),
                            ("collection", "Collection - set of objects"),
                            ("networked", "Networked - connected objects"),
                            ("hierarchical", "Hierarchical - tree structure"),
                            ("linear", "Linear - ordered sequence"),
                        ],
                        default="atomic",
                        help_text="Underlying organizational structure",
                        max_length=20,
                        verbose_name="structure",
                    ),
                ),
                (
                    "aggregation_level",
                    models.IntegerField(
                        choices=[
                            (1, "Level 1 - Raw media/fragment"),
                            (2, "Level 2 - Lesson/unit"),
                            (3, "Level 3 - Course/module"),
                            (4, "Level 4 - Program/curriculum"),
                        ],
                        default=1,
                        help_text="Functional granularity of this learning object",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="aggregation level",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "heritage_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lom_general",
                        to="heritage.heritageitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "LOM General Metadata",
                "verbose_name_plural": "LOM General Metadata",
            },
        ),
        migrations.CreateModel(
            name="LOMEducational",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interactivity_type",
                    models.CharField(
                        choices=[
                            ("active", "Active - learning by doing"),
                            ("expositive", "Expositive - learning by reading/watching"),
                            ("mixed", "Mixed - combination"),
                        ],
                        default="expositive",
                        help_text="Type of interactivity supported",
                        max_length=20,
                        verbose_name="interactivity type",
                    ),
                ),
                (
                    "learning_resource_type",
                    models.CharField(
                        choices=[
                            ("exercise", "Exercise"),
                            ("simulation", "Simulation"),
                            ("questionnaire", "Questionnaire"),
                            ("diagram", "Diagram"),
                            ("figure", "Figure"),
                            ("graph", "Graph"),
                            ("index", "Index"),
                            ("slide", "Slide"),
                            ("table", "Table"),
                            ("narrative_text", "Narrative Text"),
                            ("exam", "Exam"),
                            ("experiment", "Experiment"),
                            ("problem_statement", "Problem Statement"),
                            ("self_assessment", "Self Assessment"),
                            ("lecture", "Lecture"),
                        ],
                        default="narrative_text",
                        help_text="Specific kind of learning object",
                        max_length=30,
                        verbose_name="learning resource type",
                    ),
                ),
                (
                    "interactivity_level",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="medium",
                        help_text="Degree of interactivity",
                        max_length=20,
                        verbose_name="interactivity level",
                    ),
                ),
                (
                    "semantic_density",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="medium",
                        help_text="Subjective measure of learning object usefulness",
                        max_length=20,
                        verbose_name="semantic density",
                    ),
                ),
                (
                    "intended_end_user_role",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("author", "Author"),
                            ("learner", "Learner"),
                            ("manager", "Manager"),
                        ],
                        default="learner",
                        help_text="Principal user(s) for which this learning object was designed",
                        max_length=20,
                        verbose_name="intended end user role",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("school", "School - Primary/Secondary Education"),
                            ("higher_education", "Higher Education - University"),
                            ("training", "Training - Professional Development"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Principal environment within which learning is intended to occur",
                        max_length=30,
                        verbose_name="context",
                    ),
                ),
                (
                    "typical_age_range",
                    models.CharField(
                        blank=True,
                        help_text='Age of the typical intended user (e.g., "7-9", "18+")',
                        max_length=50,
                        verbose_name="typical age range",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("very_easy", "Very Easy"),
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("difficult", "Difficult"),
                            ("very_difficult", "Very Difficult"),
                        ],
                        default="medium",
                        help_text="How hard it is to work through this learning object",
                        max_length=20,
                        verbose_name="difficulty",
                    ),
                ),
                (
                    "typical_learning_time",
                    models.CharField(
                        blank=True,
                        help_text='Approximate time it takes to work with this learning object (e.g., "PT30M" for 30 minutes)',
                        max_length=50,
                        verbose_name="typical learning time",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Comments on how this learning object is to be used",
                        verbose_name="description",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("es", "Spanish"),
                            ("en", "English"),
                            ("qu", "Quechua"),
                        ],
                        default="es",
                        help_text="Human language of the intended user",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lom_general",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educational",
                        to="education.lomgeneral",
                    ),
                ),
            ],
            options={
                "verbose_name": "LOM Educational Metadata",
                "verbose_name_plural": "LOM Educational Metadata",
            },
        ),
        migrations.CreateModel(
            name="LOMClassification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("discipline", "Discipline - Disciplinary taxonomy"),
                            ("idea", "Idea - Idea taxonomy"),
                            ("prerequisite", "Prerequisite - Prerequisites"),
                            (
                                "educational_objective",
                                "Educational Objective - Learning objectives",
                            ),
                            (
                                "accessibility_restrictions",
                                "Accessibility Restrictions - Access limitations",
                            ),
                            ("educational_level", "Educational Level - Grade level"),
                            ("skill_level", "Skill Level - Skill requirements"),
                            (
                                "security_level",
                                "Security Level - Security classification",
                            ),
                            ("competency", "Competency - Competencies addressed"),
                        ],
                        help_text="Characteristic described by this classification",
                        max_length=40,
                        verbose_name="purpose",
                    ),
                ),
                (
                    "taxon_source",
                    models.CharField(
                        help_text="Name of the classification system",
                        max_length=200,
                        verbose_name="taxon source",
                    ),
                ),
                (
                    "taxon_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier of the taxon",
                        max_length=100,
                        verbose_name="taxon id",
                    ),
                ),
                (
                    "taxon_entry",
                    models.CharField(
                        help_text="Label of the taxon",
                        max_length=500,
                        verbose_name="taxon entry",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the learning object relative to its classification",
                        verbose_name="description",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Keywords describing the classification (comma-separated)",
                        verbose_name="keywords",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lom_general",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="education.lomgeneral",
                    ),
                ),
            ],
            options={
                "verbose_name": "LOM Classification",
                "verbose_name_plural": "LOM Classifications",
            },
        ),
        migrations.CreateModel(
            name="LOMLifeCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Edition of this learning object",
                        max_length=50,
                        verbose_name="version",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("final", "Final"),
                            ("revised", "Revised"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="draft",
                        help_text="Completion status or condition",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lom_general",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle",
                        to="education.lomgeneral",
                    ),
                ),
            ],
            options={
                "verbose_name": "LOM Life Cycle",
                "verbose_name_plural": "LOM Life Cycles",
            },
        ),
        migrations.CreateModel(
            name="LOMContributor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("author", "Author"),
                            ("publisher", "Publisher"),
                            ("unknown", "Unknown"),
                            ("initiator", "Initiator"),
                            ("terminator", "Terminator"),
                            ("validator", "Validator"),
                            ("editor", "Editor"),
                            ("graphical_designer", "Graphical Designer"),
                            ("technical_implementer", "Technical Implementer"),
                            ("content_provider", "Content Provider"),
                            ("technical_validator", "Technical Validator"),
                            ("educational_validator", "Educational Validator"),
                            ("script_writer", "Script Writer"),
                            ("instructional_designer", "Instructional Designer"),
                            ("subject_matter_expert", "Subject Matter Expert"),
                        ],
                        help_text="Kind of contribution",
                        max_length=30,
                        verbose_name="role",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        help_text="Name of contributing person or organization",
                        max_length=200,
                        verbose_name="entity",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Date of contribution",
                        null=True,
                        verbose_name="date",
                    ),
                ),
                (
                    "lifecycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="education.lomlifecycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "LOM Contributor",
                "verbose_name_plural": "LOM Contributors",
            },
        ),
        migrations.CreateModel(
            name="LOMRights",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cost",
                    models.BooleanField(
                        default=False,
                        help_text="Whether use of this learning object requires payment",
                        verbose_name="cost",
                    ),
                ),
                (
                    "copyright_and_other_restrictions",
                    models.BooleanField(
                        default=True,
                        help_text="Whether copyright or other restrictions apply",
                        verbose_name="copyright and other restrictions",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Comments on the conditions of use of this learning object",
                        verbose_name="description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lom_general",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rights",
                        to="education.lomgeneral",
                    ),
                ),
            ],
            options={
                "verbose_name": "LOM Rights",
                "verbose_name_plural": "LOM Rights",
            },
        ),
    ]
