# Generated by Django 5.1.3 on 2025-12-10 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
        ("heritage", "0005_annotation_content_en_annotation_content_es_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "name_es",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "name_qu",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "resource category",
                "verbose_name_plural": "resource categories",
            },
        ),
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "name_es",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "name_qu",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "resource type",
                "verbose_name_plural": "resource types",
            },
        ),
        migrations.AddField(
            model_name="lomclassification",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Description of the learning object relative to its classification",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="lomclassification",
            name="description_es",
            field=models.TextField(
                blank=True,
                help_text="Description of the learning object relative to its classification",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="lomclassification",
            name="description_qu",
            field=models.TextField(
                blank=True,
                help_text="Description of the learning object relative to its classification",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="lomclassification",
            name="keywords_en",
            field=models.TextField(
                blank=True,
                help_text="Keywords describing the classification (comma-separated)",
                null=True,
                verbose_name="keywords",
            ),
        ),
        migrations.AddField(
            model_name="lomclassification",
            name="keywords_es",
            field=models.TextField(
                blank=True,
                help_text="Keywords describing the classification (comma-separated)",
                null=True,
                verbose_name="keywords",
            ),
        ),
        migrations.AddField(
            model_name="lomclassification",
            name="keywords_qu",
            field=models.TextField(
                blank=True,
                help_text="Keywords describing the classification (comma-separated)",
                null=True,
                verbose_name="keywords",
            ),
        ),
        migrations.AddField(
            model_name="lomeducational",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Comments on how this learning object is to be used",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="lomeducational",
            name="description_es",
            field=models.TextField(
                blank=True,
                help_text="Comments on how this learning object is to be used",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="lomeducational",
            name="description_qu",
            field=models.TextField(
                blank=True,
                help_text="Comments on how this learning object is to be used",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="coverage_en",
            field=models.TextField(
                blank=True,
                help_text="Time, culture, geography or region to which this learning object applies",
                null=True,
                verbose_name="coverage",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="coverage_es",
            field=models.TextField(
                blank=True,
                help_text="Time, culture, geography or region to which this learning object applies",
                null=True,
                verbose_name="coverage",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="coverage_qu",
            field=models.TextField(
                blank=True,
                help_text="Time, culture, geography or region to which this learning object applies",
                null=True,
                verbose_name="coverage",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="description_en",
            field=models.TextField(
                help_text="Description of the content of this learning object",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="description_es",
            field=models.TextField(
                help_text="Description of the content of this learning object",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="description_qu",
            field=models.TextField(
                help_text="Description of the content of this learning object",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="keywords_en",
            field=models.TextField(
                blank=True,
                help_text="Keywords or phrases describing the topic (comma-separated)",
                null=True,
                verbose_name="keywords",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="keywords_es",
            field=models.TextField(
                blank=True,
                help_text="Keywords or phrases describing the topic (comma-separated)",
                null=True,
                verbose_name="keywords",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="keywords_qu",
            field=models.TextField(
                blank=True,
                help_text="Keywords or phrases describing the topic (comma-separated)",
                null=True,
                verbose_name="keywords",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="title_en",
            field=models.CharField(
                help_text="Name given to this learning object",
                max_length=500,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="title_es",
            field=models.CharField(
                help_text="Name given to this learning object",
                max_length=500,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AddField(
            model_name="lomgeneral",
            name="title_qu",
            field=models.CharField(
                help_text="Name given to this learning object",
                max_length=500,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.CreateModel(
            name="EducationalResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "title_es",
                    models.CharField(max_length=200, null=True, verbose_name="title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, null=True, verbose_name="title"),
                ),
                (
                    "title_qu",
                    models.CharField(max_length=200, null=True, verbose_name="title"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "description_es",
                    models.TextField(null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="description"),
                ),
                (
                    "description_qu",
                    models.TextField(null=True, verbose_name="description"),
                ),
                ("content", models.TextField(verbose_name="content")),
                ("content_es", models.TextField(null=True, verbose_name="content")),
                ("content_en", models.TextField(null=True, verbose_name="content")),
                ("content_qu", models.TextField(null=True, verbose_name="content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="educational_resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "related_heritage_items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="educational_resources",
                        to="heritage.heritageitem",
                        verbose_name="related heritage items",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="education.resourcecategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="education.resourcetype",
                        verbose_name="resource type",
                    ),
                ),
            ],
            options={
                "verbose_name": "educational resource",
                "verbose_name_plural": "educational resources",
                "ordering": ["-created_at"],
            },
        ),
    ]
