# Generated by Django 5.1.3 on 2025-12-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_lomrelation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationalresource",
            name="content_qu",
        ),
        migrations.RemoveField(
            model_name="educationalresource",
            name="description_qu",
        ),
        migrations.RemoveField(
            model_name="educationalresource",
            name="title_qu",
        ),
        migrations.RemoveField(
            model_name="lomclassification",
            name="description_qu",
        ),
        migrations.RemoveField(
            model_name="lomclassification",
            name="keywords_qu",
        ),
        migrations.RemoveField(
            model_name="lomeducational",
            name="description_qu",
        ),
        migrations.RemoveField(
            model_name="lomgeneral",
            name="coverage_qu",
        ),
        migrations.RemoveField(
            model_name="lomgeneral",
            name="description_qu",
        ),
        migrations.RemoveField(
            model_name="lomgeneral",
            name="keywords_qu",
        ),
        migrations.RemoveField(
            model_name="lomgeneral",
            name="title_qu",
        ),
        migrations.RemoveField(
            model_name="resourcecategory",
            name="name_qu",
        ),
        migrations.RemoveField(
            model_name="resourcetype",
            name="name_qu",
        ),
    ]
