# Generated by Django 5.1.3 on 2025-12-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_remove_educationalresource_content_qu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lomeducational",
            name="learning_resource_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                    ("document", "Document"),
                    ("exercise", "Exercise"),
                    ("simulation", "Simulation"),
                    ("questionnaire", "Questionnaire"),
                    ("diagram", "Diagram"),
                    ("figure", "Figure"),
                    ("graph", "Graph"),
                    ("index", "Index"),
                    ("slide", "Slide"),
                    ("table", "Table"),
                    ("narrative_text", "Narrative Text"),
                    ("exam", "Exam"),
                    ("experiment", "Experiment"),
                    ("problem_statement", "Problem Statement"),
                    ("self_assessment", "Self Assessment"),
                    ("lecture", "Lecture"),
                ],
                default="narrative_text",
                help_text="Specific kind of learning object",
                max_length=30,
                verbose_name="learning resource type",
            ),
        ),
    ]
