# Generated by Django 5.1.3 on 2026-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_lessonplan_lessonactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonactivity',
            name='instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='instructions'),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='instructions_es',
            field=models.TextField(blank=True, null=True, verbose_name='instructions'),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='materials_en',
            field=models.TextField(blank=True, null=True, verbose_name='materials'),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='materials_es',
            field=models.TextField(blank=True, null=True, verbose_name='materials'),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='lessonactivity',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='curriculum_alignment_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='curriculum alignment'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='curriculum_alignment_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='curriculum alignment'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='summary_es',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
