# Generated by Django 5.1.3 on 2026-07-01 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_lessonactivity_instructions_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='code')),
                ('subject', models.CharField(blank=True, max_length=120, verbose_name='subject')),
                ('grade_level', models.CharField(blank=True, max_length=60, verbose_name='grade level')),
                ('description', models.TextField(verbose_name='description')),
                ('description_es', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'curriculum standard',
                'verbose_name_plural': 'curriculum standards',
                'ordering': ['subject', 'grade_level', 'code'],
            },
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='standards',
            field=models.ManyToManyField(blank=True, related_name='lesson_plans', to='education.curriculumstandard', verbose_name='curriculum standards'),
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_es', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='education.lessonplan', verbose_name='lesson plan')),
            ],
            options={
                'verbose_name': 'rubric',
                'verbose_name_plural': 'rubrics',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('max_points', models.IntegerField(default=4, verbose_name='max points')),
                ('levels', models.JSONField(blank=True, default=list, verbose_name='levels')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='education.rubric', verbose_name='rubric')),
            ],
            options={
                'verbose_name': 'rubric criterion',
                'verbose_name_plural': 'rubric criteria',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('rubric', 'order'), name='unique_criterion_order_per_rubric')],
            },
        ),
    ]
