# Generated by Django 5.1.3 on 2026-07-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_backfill_riobamba_city_roles'),
        ('education', '0011_seed_curriculum_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumstandard',
            name='country',
            field=models.CharField(default='EC', help_text='ISO 3166-1 alpha-2 country the framework belongs to', max_length=2, verbose_name='country code'),
        ),
        migrations.AddField(
            model_name='curriculumstandard',
            name='framework',
            field=models.CharField(default='MinEduc', help_text='Curriculum framework/authority, e.g. MinEduc', max_length=80, verbose_name='framework'),
        ),
        migrations.AddField(
            model_name='educationalresource',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='educational_resources', to='cities.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='cities.city', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='curriculumstandard',
            name='code',
            field=models.CharField(max_length=40, verbose_name='code'),
        ),
        migrations.AddConstraint(
            model_name='curriculumstandard',
            constraint=models.UniqueConstraint(fields=('country', 'framework', 'code'), name='unique_standard_per_framework'),
        ),
    ]
